import { User, Address, Restaurant, Dish, PaymentMethod, PaymentType } from './types';

export const mockUser: User = {
  id: 'user-123',
  name: 'John Doe',
  email: 'john.doe@example.com',
  phone: '+1 (555) 123-4567',
  preferences: ['Spicy', 'Italian'],
  loyaltyPoints: 1200,
  membershipLevel: 'Gold',
};

export const mockAddresses: Address[] = [
  {
    id: 'addr-1',
    tag: 'Home',
    street: '123 Main St',
    city: 'Anytown',
    state: 'CA',
    zipCode: '90210',
    country: 'USA',
    instructions: 'Ring doorbell twice.',
    isDefault: true,
  },
  {
    id: 'addr-2',
    tag: 'Work',
    street: '456 Oak Ave',
    city: 'Anytown',
    state: 'CA',
    zipCode: '90210',
    country: 'USA',
    instructions: 'Leave at reception.',
    isDefault: false,
  },
];

export const mockPaymentMethods: PaymentMethod[] = [
  {
    id: 'pm-1',
    type: PaymentType.CREDIT_DEBIT_CARD,
    details: 'Visa ending **** 4242',
    isDefault: true,
  },
  {
    id: 'pm-2',
    type: PaymentType.WALLET,
    details: 'FlavorPay Wallet (Balance: $50)',
    isDefault: false,
  },
  {
    id: 'pm-3',
    type: PaymentType.CASH_ON_DELIVERY,
    details: 'Cash on Delivery',
    isDefault: false,
  },
];

export const mockRestaurants: Restaurant[] = [
  {
    id: 'r1',
    name: 'The Italian Bistro',
    cuisine: ['Italian', 'Pasta', 'Pizza'],
    rating: 4.5,
    deliveryTimeMinutes: 30,
    priceRange: '$$$',
    imageUrl: 'https://picsum.photos/400/250?random=1',
    address: '101 Pasta Lane, Anytown',
    description: 'Authentic Italian dishes made with love and fresh ingredients.',
    hasOffers: true,
    isVegOnly: false,
  },
  {
    id: 'r2',
    name: 'Spicy Spoon Indian',
    cuisine: ['Indian', 'Curry', 'Biryani'],
    rating: 4.8,
    deliveryTimeMinutes: 45,
    priceRange: '$$',
    imageUrl: 'https://picsum.photos/400/250?random=2',
    address: '202 Curry Road, Anytown',
    description: 'Experience the rich flavors of India, from mild to fiery spicy!',
    hasOffers: false,
    isVegOnly: false,
  },
  {
    id: 'r3',
    name: 'Green Garden Cafe',
    cuisine: ['Vegan', 'Healthy', 'Salads'],
    rating: 4.2,
    deliveryTimeMinutes: 25,
    priceRange: '$$',
    imageUrl: 'https://picsum.photos/400/250?random=3',
    address: '303 Fresh Street, Anytown',
    description: 'Fresh, organic, and delicious vegan options for a healthy lifestyle.',
    hasOffers: true,
    isVegOnly: true,
  },
  {
    id: 'r4',
    name: 'Burger Haven',
    cuisine: ['American', 'Burgers', 'Fries'],
    rating: 4.0,
    deliveryTimeMinutes: 20,
    priceRange: '$',
    imageUrl: 'https://picsum.photos/400/250?random=4',
    address: '404 Patty Place, Anytown',
    description: 'Classic American burgers, shakes, and sides for the perfect comfort meal.',
    hasOffers: false,
    isVegOnly: false,
  },
  {
    id: 'r5',
    name: 'Sushi Zen',
    cuisine: ['Japanese', 'Sushi', 'Ramen'],
    rating: 4.7,
    deliveryTimeMinutes: 35,
    priceRange: '$$$',
    imageUrl: 'https://picsum.photos/400/250?random=5',
    address: '505 Wasabi Way, Anytown',
    description: 'Finest sushi and traditional Japanese cuisine in town.',
    hasOffers: true,
    isVegOnly: false,
  },
];

export const mockDishes: Dish[] = [
  // Italian Bistro
  {
    id: 'd1',
    restaurantId: 'r1',
    name: 'Spaghetti Carbonara',
    description: 'Classic spaghetti with egg, hard cheese, cured pork, and black pepper.',
    price: 18.00,
    imageUrl: 'https://picsum.photos/300/200?random=101',
    isVeg: false,
    inStock: true,
  },
  {
    id: 'd2',
    restaurantId: 'r1',
    name: 'Margherita Pizza',
    description: 'Simple yet delicious pizza with tomato, mozzarella, and fresh basil.',
    price: 15.00,
    imageUrl: 'https://picsum.photos/300/200?random=102',
    isVeg: true,
    inStock: true,
    variants: [
      {
        name: 'Size',
        options: [
          { name: 'Small', price: 0 },
          { name: 'Medium', price: 3 },
          { name: 'Large', price: 5 },
        ],
      },
    ],
    addOns: [
      { id: 'extra-cheese', name: 'Extra Cheese', price: 2 },
      { id: 'olives', name: 'Olives', price: 1 },
    ],
  },
  {
    id: 'd3',
    restaurantId: 'r1',
    name: 'Tiramisu',
    description: 'Classic Italian dessert with coffee-soaked ladyfingers, mascarpone cheese, and cocoa.',
    price: 8.50,
    imageUrl: 'https://picsum.photos/300/200?random=103',
    isVeg: true,
    inStock: true,
  },
  // Spicy Spoon Indian
  {
    id: 'd4',
    restaurantId: 'r2',
    name: 'Butter Chicken',
    description: 'Creamy tomato-based curry with tender chicken pieces, a mild Indian classic.',
    price: 16.50,
    imageUrl: 'https://picsum.photos/300/200?random=104',
    isVeg: false,
    inStock: true,
  },
  {
    id: 'd5',
    restaurantId: 'r2',
    name: 'Vegetable Biryani',
    description: 'Aromatic basmati rice cooked with mixed vegetables and Indian spices.',
    price: 14.00,
    imageUrl: 'https://picsum.photos/300/200?random=105',
    isVeg: true,
    inStock: true,
    variants: [
      {
        name: 'Spicy Level',
        options: [
          { name: 'Mild', price: 0 },
          { name: 'Medium', price: 0 },
          { name: 'Hot', price: 0 },
        ],
      },
    ],
  },
  {
    id: 'd6',
    restaurantId: 'r2',
    name: 'Garlic Naan',
    description: 'Soft, fluffy Indian bread infused with garlic.',
    price: 4.00,
    imageUrl: 'https://picsum.photos/300/200?random=106',
    isVeg: true,
    inStock: true,
  },
  // Green Garden Cafe
  {
    id: 'd7',
    restaurantId: 'r3',
    name: 'Quinoa Power Bowl',
    description: 'Nutrient-packed bowl with quinoa, roasted vegetables, avocado, and tahini dressing.',
    price: 13.50,
    imageUrl: 'https://picsum.photos/300/200?random=107',
    isVeg: true,
    inStock: true,
  },
  {
    id: 'd8',
    restaurantId: 'r3',
    name: 'Lentil Soup',
    description: 'Hearty and wholesome lentil soup, perfect for a light meal.',
    price: 9.00,
    imageUrl: 'https://picsum.photos/300/200?random=108',
    isVeg: true,
    inStock: true,
  },
  // Burger Haven
  {
    id: 'd9',
    restaurantId: 'r4',
    name: 'Classic Cheeseburger',
    description: 'Beef patty, cheddar cheese, lettuce, tomato, onion, pickles, special sauce.',
    price: 12.00,
    imageUrl: 'https://picsum.photos/300/200?random=109',
    isVeg: false,
    inStock: true,
  },
  {
    id: 'd10',
    restaurantId: 'r4',
    name: 'Veggie Burger',
    description: 'Plant-based patty, lettuce, tomato, onion, pickles, vegan mayo.',
    price: 11.50,
    imageUrl: 'https://picsum.photos/300/200?random=110',
    isVeg: true,
    inStock: true,
  },
  // Sushi Zen
  {
    id: 'd11',
    restaurantId: 'r5',
    name: 'California Roll',
    description: 'Crab meat, avocado, cucumber, and rice wrapped in nori.',
    price: 10.00,
    imageUrl: 'https://picsum.photos/300/200?random=111',
    isVeg: false,
    inStock: true,
  },
  {
    id: 'd12',
    restaurantId: 'r5',
    name: 'Spicy Tuna Roll',
    description: 'Tuna mixed with spicy mayo and green onions.',
    price: 12.00,
    imageUrl: 'https://picsum.photos/300/200?random=112',
    isVeg: false,
    inStock: true,
  },
];
